sudo: true

language: go

go:
  - "1.15.x"

service:
  - docker

env:
  - GO111MODULE=on

install: true

jobs:
  include:
    - stage: build docker image
      script:
      - export DHEALTHREPO=$DOCKER_NAMESPACE/mmesim-fsb-dev
      - export VERSION=v0.1.20
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o build/_output/bin/mmesim-fsb -gcflags all=-trimpath=${GOPATH} -asmflags all=-trimpath=${GOPATH} -tags=v1 ./cmd/fsb/...
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DHEALTHREPO:$VERSION -f build/Dockerfile.mmesim-fsb .
      - docker tag $DHEALTHREPO:$VERSION $DHEALTHREPO:latest
      - docker tag $DHEALTHREPO:$VERSION $DHEALTHREPO:travis-$TRAVIS_BUILD_NUMBER
      - docker push $DHEALTHREPO
    - stage: test docker image
      script:
      - export DHEALTHREPO=$DOCKER_NAMESPACE/mmesim-fsb-dev
      - export VERSION=v0.1.20
      - docker run -d --name test_mme $DHEALTHREPO:$VERSION
      - docker ps | grep -q test_mme
